---
- name: Install openjdk-11
  hosts: localhost
  tasks:
    - name: Install openjdk-11 Pkg for Debian
      apt:
        name: openjdk11
        state: present
        update_cache: yes
      become: yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Install openjdk-11 Pkg for RedHat
      yum:
        name: openjdk11
        state: present
        update_cache: yes
      become: yes
      when: ansible_os_family == "RedHat"

    - name: Install openjdk-11 Pkg for Alpine
      apk:
        name: openjdk11
        state: present
        update_cache: yes
      become: yes
      when: ansible_os_family == "Alpine"
