---
- name: Install apache
  hosts: localhost
  tasks:
  - name: Check if Apache is installed
    command: which apache2
    register: apache_check
    ignore_errors: yes

  - block:
    - name: Update the system
      apt: update_cache=true
      become: yes

    - name: Install apache Pkg
      apt: name: ['apache2'] state=present update_cache=yes
      become: yes

    when: apache_check.rc != 0
